# Generated by Django 5.1.15 on 2026-07-25 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('email', 'Email'), ('domain', 'Domain'), ('username', 'Username'), ('ip', 'IP Address'), ('phone', 'Phone')], max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('alerting', 'Alerting'), ('error', 'Error')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('breach_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitoring_monitor',
                'ordering': ['-created_at'],
            },
        ),
    ]
