# Generated by Django 5.1.15 on 2026-07-25 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('email', 'Email'), ('domain', 'Domain'), ('username', 'Username'), ('ip', 'IP Address'), ('phone', 'Phone')], max_length=20)),
                ('source', models.CharField(choices=[('dehashed', 'Dehashed'), ('hibp', 'Have I Been Pwned'), ('internal', 'Internal')], default='dehashed', max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_searchresult',
                'ordering': ['-created_at'],
            },
        ),
    ]
