# Generated by Django 5.1.15 on 2026-07-25 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('breach', 'Breach Analysis'), ('executive', 'Executive Summary'), ('compliance', 'Compliance Report'), ('domain', 'Domain Security'), ('monitoring', 'Monitoring Summary')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
